### 未知api
GET http://localhost:8080/tft-external/v1/active-game

### 未知api
GET http://localhost:8080/tft/v1/matches/1090

### 获取局内玩家信息
GET http://localhost:8080/lol-gameflow/v1/session

###
GET http://localhost:8080/lol-game-queues/v1/queues

###
POST http://localhost:8080/lol-chat/v1/conversations/c1~0ab3bf706f7dc02005e3c0fb038553cfc62fd1de/active
content-Type: application/json

{
  "body": "123"
}

###
GET http://localhost:8080/lol-chat/v1/conversations/c1~0ab3bf706f7dc02005e3c0fb038553cfc62fd1de/active


###
GET http://localhost:8080/lol-match-history/v1/products/lol/98255012-e56f-5b4c-9bcb-17b83bd7d755/matches
